### ISSUE TITLE
How to train using dakent53

### ISSUE THREAD

**Issue by vishnuvardhan58** [chingi071/Yolact_training#1]
@chingi071  I tried running python train.py , I am getting error as FileNotFoundError: [Errno 2] No such file or directory: 'weights/resnet50-19c8e357.pth' , although in the weights file I have darknet53.pth file , is there anything I need to change in the train.py file to make training work on darknet53.pth file ? can you help me with this ?

**Comment by vishnuvardhan58** [comment]
@chingi071

**Comment by chingi071** [comment]
You can try
`python train.py --config=yolact_base_config --resume=weights/darknet53.pth`
